
import Nav3 from './components/Nav3'
import './globals.css'
import { Source_Code_Pro } from 'next/font/google'
 

const inter = Source_Code_Pro({ 
  weight: '400',
  subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Nav3 />
        {children}</body>
    </html>
  )
}
